export const recommandationsList = [
  {
    title: "The Legend of Zelda: Tears of the Kingdom",
    description:
      "Sequel to BotW, but with even more 'holy crap I can actually do that?' moments. You can fuse sticks to pitchforks, build flying machines, or just yeet yourself off a sky island because why not.",
    gameplayHighlights: [
      "Massive open world stacked with sky + underground maps",
      "Fuse system makes even trash weapons feel fun",
      "Endless side quests and random weird NPCs",
    ],
    recommendation:
      "If you ever wanted to feel like MacGyver in Hyrule, this is it. I lost 3 days building a dumb cart that immediately broke, and it was glorious.",
    genre: "Action-Adventure / Open World",
    platforms: ["Nintendo Switch"],
    playtime: "80–150 hours (depending on how distracted you get)",
    rating: 9.7,
    releaseDate: "2023-05-12",
    reviewsCount: 20000,
    youtubeTrailerId: "uHGShqcAHlQ",
    youtubeGameplayId: "G_4XArDRYqY",
    youtubeReviewId: "Mmoju4qRJh0",
    amazonLink: "https://www.amazon.com/dp/B0BMFZYFDP?tag=your-affiliate-id",
  },
  {
    title: "Bloodborne",
    description:
      "Imagine Dark Souls got bit by a Victorian horror novel—fast, brutal, and dripping with nightmare fuel. You’re basically running around in a gothic fever dream where every alley hides something that wants to eat you.",
    gameplayHighlights: [
      "Fast-paced, dodge-heavy combat",
      "Transforming trick weapons mid-fight",
      "Bosses straight out of Lovecraft’s nightmares",
    ],
    recommendation:
      "If you want that sweet mix of adrenaline and terror, Bloodborne will own your soul. You’ll rage, but beating a boss feels like becoming a legend.",
    genre: "Action RPG",
    platforms: ["PS4"],
    playtime: "40–60 hours",
    rating: 9.6,
    releaseDate: "2015-03-24",
    reviewsCount: 32000,
    youtubeTrailerId: "G203e1HhixY",
    youtubeGameplayId: "10bB6NQ3l3k",
    youtubeReviewId: "alGe6SUl4nE",
    amazonLink: "https://www.amazon.com/dp/B00KVR4HEC?tag=your-affiliate-id",
  },
  {
    title: "Persona 5 Royal",
    description:
      "Half stylish anime, half life-sim, and half turn-based JRPG (yeah that’s three halves, deal with it). You juggle school, friendships, and saving Tokyo by stealing the hearts of evil adults.",
    gameplayHighlights: [
      "Turn-based combat with flashy All-Out Attacks",
      "Life sim elements: hang out, study, date",
      "Ridiculously stylish menus and music",
    ],
    recommendation:
      "If you’re into JRPGs and anime vibes, this one’s a time sink in the best way possible. Just clear your calendar—it eats 100+ hours easy.",
    genre: "JRPG",
    platforms: ["PS4", "PS5", "Xbox Series X|S", "PC", "Switch"],
    playtime: "100–120 hours",
    rating: 9.7,
    releaseDate: "2020-03-31",
    reviewsCount: 28000,
    youtubeTrailerId: "pPCLpzWOSLw",
    youtubeGameplayId: "9KfMRN_hyKQ",
    youtubeReviewId: "0PqIx1dz9Cg",
    amazonLink: "https://www.amazon.com/dp/B08KH53VHZ?tag=your-affiliate-id",
  },
  {
    title: "The Witcher 3: Wild Hunt",
    description:
      "Geralt, the monster-slaying grump with the world’s best beard, searches for his adopted daughter while everyone else distracts him with politics, booze, or Gwent.",
    gameplayHighlights: [
      "A story with moral choices that actually matter",
      "Side quests better than most games’ main quests",
      "Two massive DLCs that feel like full games",
    ],
    recommendation:
      "You’ll start for the epic monster hunts, stay for the writing, and realize 40 hours later that you’re addicted to Gwent.",
    genre: "RPG / Open World",
    platforms: ["PS5", "PS4", "Xbox Series X|S", "Switch", "PC"],
    playtime: "100–200 hours (plus DLC)",
    rating: 9.8,
    releaseDate: "2015-05-19",
    reviewsCount: 50000,
    youtubeTrailerId: "c0i88t0Kacs",
    youtubeGameplayId: "vBB1XuAM6wk",
    youtubeReviewId: "n8i53TtQ6AQ",
    amazonLink: "https://www.amazon.com/dp/B00WTI6XJ4?tag=your-affiliate-id",
  },
  {
    title: "Hollow Knight",
    description:
      "Looks cute with its little bug knight, but it’s secretly a hardcore 2D adventure that’ll chew you up and spit you out. Exploring Hallownest feels like diving into a dark fairytale.",
    gameplayHighlights: [
      "Precision platforming and tight combat",
      "A giant interconnected world full of secrets",
      "Epic bosses that test your patience and skill",
    ],
    recommendation:
      "If you like challenge and exploration, this is pure indie perfection. Plus, the soundtrack will stick in your head for weeks.",
    genre: "Metroidvania / Action-Adventure",
    platforms: ["PC", "Switch", "PS4", "Xbox One"],
    playtime: "30–60 hours",
    rating: 9.5,
    releaseDate: "2017-02-24",
    reviewsCount: 27000,
    youtubeTrailerId: "UAO2urG23S4",
    youtubeGameplayId: "XfEw1IhuP84",
    youtubeReviewId: "JDy8oCKFqZg",
    amazonLink: "https://www.amazon.com/dp/B08SWJH17P?tag=your-affiliate-id",
  },
  {
    title: "Elden Ring",
    description:
      "Dark Souls went open world and it’s as insane as it sounds. You’re dropped into The Lands Between with zero hand-holding, just a horse, a sword, and a lot of ways to die.",
    gameplayHighlights: [
      "Huge open world with secrets in every corner",
      "Boss fights that make your palms sweat",
      "Tons of builds: magic, melee, or pure chaos",
    ],
    recommendation:
      "If you ever wanted Dark Souls mixed with Skyrim, this is it. Just be ready to lose weekends exploring and dying gloriously.",
    genre: "Action RPG / Open World",
    platforms: ["PS5", "PS4", "Xbox Series X|S", "PC"],
    playtime: "80–120 hours",
    rating: 9.7,
    releaseDate: "2022-02-25",
    reviewsCount: 65000,
    youtubeTrailerId: "E3Huy2cdih0",
    youtubeGameplayId: "JldMvQMO_5U",
    youtubeReviewId: "JLD3SWXUJtA",
    amazonLink: "https://www.amazon.com/dp/B097TTDPZW?tag=your-affiliate-id",
  },
  {
    title: "God of War Ragnarök",
    description:
      "Dad Kratos is back, swinging the Leviathan Axe and arguing with his now-teen son Atreus. It’s myth-smashing action mixed with emotional storytelling that’ll punch you in the feels.",
    gameplayHighlights: [
      "Brutal axe-throwing combat that never gets old",
      "Huge Norse myth boss battles",
      "Touching father-son story with epic scale",
    ],
    recommendation:
      "If you liked 2018’s God of War, this is the bigger, better sequel. More gods, more drama, more ‘BOY!’.",
    genre: "Action-Adventure",
    platforms: ["PS5", "PS4"],
    playtime: "40–60 hours",
    rating: 9.6,
    releaseDate: "2022-11-09",
    reviewsCount: 42000,
    youtubeTrailerId: "hFGL_XPp5oQ",
    youtubeGameplayId: "mK7_TBfnE7Q",
    youtubeReviewId: "NxAmFLtZM0g",
    amazonLink: "https://www.amazon.com/dp/B0B2J38HC6?tag=your-affiliate-id",
  },
  {
    title: "The Legend of Zelda: Breath of the Wild",
    description:
      "Link wakes up after 100 years of sleep, shrugs, and then decides to climb every mountain, cook weird food, and accidentally set forests on fire. A sandbox adventure like no other.",
    gameplayHighlights: [
      "Climb literally anything",
      "Physics-based puzzles and wacky experiments",
      "A world that rewards curiosity and chaos",
    ],
    recommendation:
      "If you ever wanted pure freedom in a Zelda game, this is the gold standard. You’ll wander, experiment, and forget the main quest for hours.",
    genre: "Action-Adventure / Open World",
    platforms: ["Switch"],
    playtime: "60–100 hours",
    rating: 9.9,
    releaseDate: "2017-03-03",
    reviewsCount: 70000,
    youtubeTrailerId: "zw47_q9wbBE",
    youtubeGameplayId: "1rPxiXXxftE",
    youtubeReviewId: "VbI7VYSBZ2Y",
    amazonLink: "https://www.amazon.com/dp/B01MS6MO77?tag=your-affiliate-id",
  },
  {
    title: "Red Dead Redemption 2",
    description:
      "Cowboy simulator 3000. You’re Arthur Morgan, a gunslinger who can rob trains, hunt deer, play poker, and grow the best beard in gaming history.",
    gameplayHighlights: [
      "Massive, living open world with crazy detail",
      "Gunfights and duels straight out of western movies",
      "A gripping outlaw story with emotional weight",
    ],
    recommendation:
      "If you like open worlds that feel alive, this one’s unmatched. Just don’t get too attached to your horse… trust me.",
    genre: "Action-Adventure / Open World",
    platforms: ["PS5", "PS4", "Xbox Series X|S", "PC"],
    playtime: "60–120 hours",
    rating: 9.8,
    releaseDate: "2018-10-26",
    reviewsCount: 68000,
    youtubeTrailerId: "eaW0tYpxyp0",
    youtubeGameplayId: "lH4AO5K0Y8M",
    youtubeReviewId: "eaO_zr2vS18",
    amazonLink: "https://www.amazon.com/dp/B01MXLXZ0D?tag=your-affiliate-id",
  },
  {
    title: "Super Mario Odyssey",
    description:
      "Mario trades power-ups for a living hat named Cappy, and together they possess everything from T-Rexes to Goombas. It’s classic Mario platforming with a huge open twist.",
    gameplayHighlights: [
      "Creative worlds packed with hidden Moons",
      "Hat possession mechanic that changes everything",
      "Tons of post-game challenges for completionists",
    ],
    recommendation:
      "If you grew up on Mario, this is like pure joy injected into your Switch. Perfect mix of nostalgia and fresh ideas.",
    genre: "Platformer / Adventure",
    platforms: ["Switch"],
    playtime: "20–50 hours",
    rating: 9.7,
    releaseDate: "2017-10-27",
    reviewsCount: 60000,
    youtubeTrailerId: "5kcdRBHM7kM",
    youtubeGameplayId: "1i8gzHJ2_E8",
    youtubeReviewId: "6QNd4Zhyqf0",
    amazonLink: "https://www.amazon.com/dp/B01MY7GHKJ?tag=your-affiliate-id",
  },
  {
    title: "Final Fantasy VII Remake",
    description:
      "Cloud and his giant sword are back, but now in HD with real-time combat and fully fleshed-out Midgar. It’s nostalgia with modern flair.",
    gameplayHighlights: [
      "Hybrid real-time and tactical combat system",
      "Expanded story arcs for classic characters",
      "Epic soundtrack reimagined with full orchestra",
    ],
    recommendation:
      "If you loved the original or just want a flashy modern JRPG, this remake nails it. Just don’t expect the full story in one game.",
    genre: "JRPG / Action",
    platforms: ["PS5", "PS4", "PC"],
    playtime: "30–50 hours",
    rating: 9.3,
    releaseDate: "2020-04-10",
    reviewsCount: 35000,
    youtubeTrailerId: "ERgrFVhL-n4",
    youtubeGameplayId: "b5rQGbCn6pY",
    youtubeReviewId: "V6UiJjUth9A",
    amazonLink: "https://www.amazon.com/dp/B08TGH4NJS?tag=your-affiliate-id",
  },
  {
    title: "Minecraft",
    description:
      "The blocky sandbox where you can do literally anything—build castles, survive zombie hordes, or just dig a really deep hole. Your imagination is the limit.",
    gameplayHighlights: [
      "Creative mode for unlimited building",
      "Survival mode with crafting and danger",
      "Multiplayer worlds to mess around with friends",
    ],
    recommendation:
      "Whether you’re a builder, adventurer, or troll, Minecraft never gets old. It’s the ultimate digital Lego set.",
    genre: "Sandbox / Survival",
    platforms: ["PS5", "PS4", "Xbox Series X|S", "Switch", "PC", "Mobile"],
    playtime: "Endless",
    rating: 9.5,
    releaseDate: "2011-11-18",
    reviewsCount: 90000,
    youtubeTrailerId: "MmB9b5njVbA",
    youtubeGameplayId: "MmB9b5njVbA",
    youtubeReviewId: "HfSXyxAzw_4",
    amazonLink: "https://www.amazon.com/dp/B009ZYFY3S?tag=your-affiliate-id",
  },
  {
    title: "Sekiro: Shadows Die Twice",
    description:
      "FromSoftware takes a break from dark fantasy and throws you into a samurai revenge tale with insane sword combat and a grappling hook. Precision is everything.",
    gameplayHighlights: [
      "Parry-based combat that rewards timing",
      "Stealth assassinations and vertical mobility",
      "Some of the hardest bosses FromSoft has made",
    ],
    recommendation:
      "If you want to feel like a true sword master (after hours of dying), Sekiro is peak challenge gaming. The first time you deflect a boss combo, you’ll cheer out loud.",
    genre: "Action-Adventure / Soulslike",
    platforms: ["PS5", "PS4", "Xbox Series X|S", "PC"],
    playtime: "30–50 hours",
    rating: 9.4,
    releaseDate: "2019-03-22",
    reviewsCount: 37000,
    youtubeTrailerId: "rXMX4YJ7Lks",
    youtubeGameplayId: "JJC9w9y3tQo",
    youtubeReviewId: "yXOMk_4KUbw",
    amazonLink: "https://www.amazon.com/dp/B0797Y8J5M?tag=your-affiliate-id",
  },
  {
    title: "Horizon Forbidden West",
    description:
      "Aloy is back, exploring a gorgeous post-apocalyptic West full of robot dinos and insane vistas. Combat is fluid, story is gripping, and the world is breathtaking.",
    gameplayHighlights: [
      "Dynamic battles against massive machines",
      "Exploration across stunning open-world biomes",
      "Crafting and skill trees to suit your playstyle",
    ],
    recommendation:
      "If you loved Horizon Zero Dawn, this sequel cranks everything up—visuals, story, and epic encounters.",
    genre: "Action RPG / Open World",
    platforms: ["PS5", "PS4"],
    playtime: "50–80 hours",
    rating: 9.5,
    releaseDate: "2022-02-18",
    reviewsCount: 30000,
    youtubeTrailerId: "u2iZee1qPKA",
    youtubeGameplayId: "6CFOqL0yH7A",
    youtubeReviewId: "dR1Eo0jYp5k",
    amazonLink: "https://www.amazon.com/dp/B09TR5Z2R3?tag=your-affiliate-id",
  },
  {
    title: "Ghost of Tsushima",
    description:
      "Samurai action at its finest. You play Jin, defending Tsushima Island from Mongol invaders while exploring gorgeous landscapes, sneaking through bamboo forests, and dueling in cinematic combat.",
    gameplayHighlights: [
      "Fluid swordplay with precise timing",
      "Open-world exploration with side quests and collectibles",
      "Stunning visuals and immersive Japanese setting",
    ],
    recommendation:
      "If you love cinematic samurai adventures and gorgeous open worlds, Ghost of Tsushima delivers on all fronts.",
    genre: "Action-Adventure / Open World",
    platforms: ["PS5", "PS4"],
    playtime: "30–50 hours",
    rating: 9.3,
    releaseDate: "2020-07-17",
    reviewsCount: 28000,
    youtubeTrailerId: "pV0dNw4u0gU",
    youtubeGameplayId: "Q5c2zH84trU",
    youtubeReviewId: "rJvXw6l_4d4",
    amazonLink: "https://www.amazon.com/dp/B08BKTL9CT?tag=your-affiliate-id",
  },
  {
    title: "Splatoon 3",
    description:
      "Ink everywhere! Squid kids are back, shooting paint, splatting turf, and showing off style in the ultimate colorful multiplayer shooter. Competitive and chaotic fun for hours.",
    gameplayHighlights: [
      "Fast-paced team-based multiplayer battles",
      "Customizable weapons and outfits",
      "New modes and maps to keep things fresh",
    ],
    recommendation:
      "If you want a fun, colorful shooter that doesn’t take itself too seriously, Splatoon 3 is perfect for you and your friends.",
    genre: "Shooter / Multiplayer",
    platforms: ["Switch"],
    playtime: "20–50 hours (plus online)",
    rating: 9.2,
    releaseDate: "2022-09-09",
    reviewsCount: 15000,
    youtubeTrailerId: "6N8x7dE3K9g",
    youtubeGameplayId: "8jHjT2sLOkM",
    youtubeReviewId: "L3kT0p8Dz9I",
    amazonLink: "https://www.amazon.com/dp/B09YKQ7G25?tag=your-affiliate-id",
  },
];
