[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  framework = "vite"
  targetPort = 5173
  port = 8888
  functions = "netlify/functions"

[secrets_scan]
  omit_keys = [
    "VITE_API_KEY",
    "VITE_PROJECT_ID",
    "VITE_APP_ID",
    "VITE_AUTH_DOMAIN",
    "VITE_STORAGE_BUCKET",
    "VITE_MEASUREMENT_ID",
    "VITE_MESSAGING_SENDER_ID"
  ]
